export const LEVEL_TITLES: Record<string, Record<number, string>> = {
  global: {
    1: 'Newcomer',
    5: 'Student',
    10: 'Learner',
    15: 'Scholar',
    20: 'Apprentice',
    25: 'Adept',
    30: 'Expert',
    40: 'Master',
    50: 'Grandmaster',
    75: 'Sage',
    100: 'Legend',
  },
  ENGLISH: {
    1: 'Word Seeker',
    10: 'Phrase Builder',
    20: 'Grammar Guardian',
    30: 'Vocabulary Virtuoso',
    40: 'Syntax Sage',
    50: 'Eloquent Expert',
    75: 'Linguistic Luminary',
    100: 'Language Legend',
  },
  MATHEMATICS: {
    1: 'Number Novice',
    10: 'Equation Explorer',
    20: 'Problem Solver',
    30: 'Formula Finder',
    40: 'Calculation Champion',
    50: 'Math Mastermind',
    75: 'Theorem Theorist',
    100: 'Mathematical Legend',
  },
  COMPUTER_SCIENCE: {
    1: 'Code Curious',
    10: 'Bug Hunter',
    20: 'Algorithm Apprentice',
    30: 'Debug Demon',
    40: 'System Architect',
    50: 'Code Wizard',
    75: 'Binary Sage',
    100: 'Programming Legend',
  },
};
